version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=solar_wind_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgre@host.docker.internal:5432/solar_wind_db
    volumes:
      - ./datasets:/app/datasets
      - ./models:/app/models