version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgre@host.docker.internal:5432/solar_wind_db
    volumes:
      - ./datasets:/app/datasets
      - ./models:/app/models