"""
app/models/report.py – SQLAlchemy ORM model for generated reports.
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from app.database.database import Base


class Report(Base):
    """
    ORM model mapped to the 'reports' table.
    Stores metadata and file paths for reports generated by users.
    """

    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    title = Column(String(255), nullable=False)
    report_type = Column(String(50), nullable=False)
    file_path = Column(String(500), nullable=True)
    status = Column(String(50), default="ready")

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="reports")

    def __repr__(self) -> str:
        return f"<Report id={self.id} title={self.title} status={self.status}>"
