"""
app/services/financial_analysis.py – Financial Analysis Module

Provides logic to estimate the financial viability of a renewable energy project,
including revenue, total project cost, payback period, and Return on Investment (ROI).
"""
from typing import Dict, Any

def estimate_annual_revenue(annual_energy_yield_mwh: float, electricity_tariff_per_kwh: float) -> float:
    """
    Estimate the annual revenue generated by the renewable energy plant.
    
    Args:
        annual_energy_yield_mwh: Total annual energy generated in Megawatt-hours (MWh).
        electricity_tariff_per_kwh: The rate per kilowatt-hour (kWh).
        
    Returns:
        Estimated annual revenue.
    """
    if annual_energy_yield_mwh < 0 or electricity_tariff_per_kwh < 0:
        raise ValueError("Energy yield and tariff must be non-negative.")
        
    # Convert MWh to kWh (1 MWh = 1000 kWh)
    annual_yield_kwh = annual_energy_yield_mwh * 1000.0
    return round(annual_yield_kwh * electricity_tariff_per_kwh, 2)

def estimate_total_project_cost(
    installed_capacity_mw: float, 
    cost_per_mw: float, 
    additional_installation_pct: float = 0.0
) -> float:
    """
    Estimate the total project installation cost.
    
    Args:
        installed_capacity_mw: Total installed capacity in Megawatts.
        cost_per_mw: Cost to install 1 MW of capacity.
        additional_installation_pct: Additional soft costs (e.g. permitting, grid connection) as a percentage (0-100).
        
    Returns:
        Estimated total project cost.
    """
    if installed_capacity_mw < 0 or cost_per_mw < 0 or additional_installation_pct < 0:
        raise ValueError("Inputs must be non-negative.")
        
    base_cost = installed_capacity_mw * cost_per_mw
    additional_cost = base_cost * (additional_installation_pct / 100.0)
    return round(base_cost + additional_cost, 2)

def estimate_payback_period(total_project_cost: float, annual_revenue: float) -> float:
    """
    Estimate the project's payback period in years.
    
    Args:
        total_project_cost: Total initial investment.
        annual_revenue: Expected annual revenue.
        
    Returns:
        Estimated payback period in years.
    """
    if total_project_cost < 0:
        raise ValueError("Total project cost cannot be negative.")
        
    if annual_revenue <= 0:
        # If revenue is zero or negative, it will never pay back.
        return float('inf')
        
    return round(total_project_cost / annual_revenue, 2)

def calculate_roi(total_project_cost: float, annual_revenue: float, lifespan_years: int = 25) -> float:
    """
    Calculate the Return on Investment (ROI) as a percentage over the project's lifespan.
    Formula: ((Total Revenue over lifespan - Total Cost) / Total Cost) * 100
    
    Args:
        total_project_cost: Total initial investment.
        annual_revenue: Expected annual revenue.
        lifespan_years: Expected lifespan of the project in years.
        
    Returns:
        ROI as a percentage.
    """
    if total_project_cost <= 0:
        return 0.0 # Prevent division by zero, or infinite ROI
        
    total_lifetime_revenue = annual_revenue * lifespan_years
    net_profit = total_lifetime_revenue - total_project_cost
    
    roi_pct = (net_profit / total_project_cost) * 100.0
    return round(roi_pct, 2)

def generate_financial_metrics(
    annual_energy_yield_mwh: float,
    installed_capacity_mw: float,
    electricity_tariff_per_kwh: float = 0.10, # default $0.10 / kWh or ₹8 / kWh
    cost_per_mw: float = 1_000_000.0, # default 1M per MW
    additional_installation_pct: float = 10.0,
    lifespan_years: int = 25
) -> Dict[str, Any]:
    """
    Convenience function to generate all financial metrics in one go.
    """
    revenue = estimate_annual_revenue(annual_energy_yield_mwh, electricity_tariff_per_kwh)
    cost = estimate_total_project_cost(installed_capacity_mw, cost_per_mw, additional_installation_pct)
    opex = round(cost * 0.015, 2) # Assume annual OPEX is 1.5% of CAPEX
    payback = estimate_payback_period(cost, revenue)
    roi = calculate_roi(cost, revenue, lifespan_years)
    
    return {
        "annual_revenue": revenue,
        "estimated_project_cost": cost,
        "estimated_opex": opex,
        "payback_period": payback,
        "roi": roi
    }
