import React, { useState, useEffect } from 'react';
import { analysisService } from '../api/analysis';
import { FileText, Download, Calendar, MapPin, Activity, Trash2 } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const data = await analysisService.getHistory();
      setReports(data);
    } catch (err) {
      console.error("Failed to fetch reports", err);
      setError("Failed to load reports history.");
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (score) => {
    if (!score) return 'var(--text-muted)';
    if (score >= 75) return '#10b981'; // green
    if (score >= 55) return '#f59e0b'; // yellow
    return '#ef4444'; // red
  };

  const handleDownload = (report) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(31, 41, 55);
    doc.text('Site Suitability Analysis Summary', 20, 20);
    
    doc.setFontSize(14);
    doc.setTextColor(75, 85, 99);
    doc.text(`Project: ${report.site_name}`, 20, 30);
    
    // Line separator
    doc.setDrawColor(229, 231, 235);
    doc.line(20, 35, 190, 35);
    
    // Details
    doc.setFontSize(12);
    doc.setTextColor(55, 65, 81);
    
    doc.text(`Date Generated: ${new Date(report.created_at).toLocaleString()}`, 20, 45);
    doc.text(`Coordinates: ${report.latitude.toFixed(4)}° N, ${report.longitude.toFixed(4)}° E`, 20, 55);
    
    // Score & Recommendation
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Final Recommendation', 20, 75);
    
    doc.setFontSize(12);
    doc.setTextColor(55, 65, 81);
    doc.text(`Suitability Score: ${report.suitability_score ? report.suitability_score.toFixed(1) + '%' : 'N/A'}`, 20, 85);
    doc.text(`Recommended Technology: ${report.recommendation}`, 20, 95);
    
    // Environmental Data
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Key Environmental Metrics', 20, 115);
    
    doc.setFontSize(12);
    doc.setTextColor(55, 65, 81);
    doc.text(`Elevation: ${report.elevation_m ? report.elevation_m.toFixed(1) + ' m' : 'N/A'}`, 20, 125);
    doc.text(`Solar Irradiance (GHI): ${report.solar_irradiance_kwh ? report.solar_irradiance_kwh.toFixed(2) + ' kWh/m²' : 'N/A'}`, 20, 135);
    doc.text(`Wind Speed (50m): ${report.wind_speed_50m_ms ? report.wind_speed_50m_ms.toFixed(2) + ' m/s' : 'N/A'}`, 20, 145);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text('Generated by Solar & Wind Deployment Intelligence Platform', 20, 280);
    
    doc.save(`${report.site_name}_Summary.pdf`);
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this report?")) return;
    try {
      await analysisService.deleteHistory(id);
      setReports(reports.filter(r => r.id !== id));
    } catch (err) {
      console.error("Failed to delete report:", err);
      alert("Failed to delete the report. Please try again.");
    }
  };

  return (
    <div className="page-content" style={{ paddingBottom: '4rem' }}>
      <div className="page-header" style={{ marginBottom: '2rem' }}>
        <div>
          <h1 className="page-title" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <FileText size={32} color="var(--color-primary)" />
            Generated Reports
          </h1>
          <p className="page-subtitle">View and manage your historical site analysis reports</p>
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-muted)' }}>
          <span className="spinner" style={{ width: 32, height: 32, borderWidth: 3 }} />
          <p style={{ marginTop: '1rem' }}>Loading reports history…</p>
        </div>
      ) : error ? (
        <div className="card" style={{ padding: '2rem', color: '#ef4444' }}>{error}</div>
      ) : reports.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <FileText size={48} color="var(--text-muted)" style={{ marginBottom: '1rem' }} />
            <h3>No Reports Generated</h3>
            <p>Run a site analysis to automatically generate and save reports here.</p>
          </div>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '1.5rem' }}>
          {reports.map((report) => (
            <div key={report.id} className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                  <h3 style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.25rem' }}>
                    {report.site_name}
                  </h3>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-secondary)', fontSize: '0.875rem' }}>
                    <Calendar size={14} /> 
                    {new Date(report.created_at).toLocaleDateString()} at {new Date(report.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
                <div style={{ 
                  background: 'var(--bg-default)', 
                  padding: '0.5rem', 
                  borderRadius: 'var(--radius-md)', 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '0.5rem',
                  border: `1px solid ${getStatusColor(report.suitability_score)}`
                }}>
                  <span style={{ fontSize: '1.25rem', fontWeight: 800, color: getStatusColor(report.suitability_score) }}>
                    {report.suitability_score ? `${report.suitability_score.toFixed(1)}%` : 'N/A'}
                  </span>
                </div>
              </div>

              <div style={{ display: 'flex', gap: '1rem', color: 'var(--text-secondary)', fontSize: '0.875rem', marginTop: '0.5rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <MapPin size={16} color="var(--color-primary)" />
                  {report.latitude.toFixed(4)}°, {report.longitude.toFixed(4)}°
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Activity size={16} color="#f59e0b" />
                  {report.recommendation}
                </div>
              </div>

              <div style={{ marginTop: 'auto', paddingTop: '1rem', borderTop: '1px solid var(--bg-border)', display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
                 <button 
                  className="btn btn-secondary btn-sm" 
                  onClick={() => handleDownload(report)}
                  style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                 >
                   <Download size={16} /> Download
                 </button>
                 <button 
                  className="btn btn-secondary btn-sm" 
                  onClick={() => handleDelete(report.id)}
                  style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#ef4444', borderColor: 'transparent' }}
                  title="Delete Report"
                 >
                   <Trash2 size={16} />
                 </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
